// Code generated by protoc-gen-go. DO NOT EDIT.
// source: any.proto

package any

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Any struct {
	IsPb                 bool     `protobuf:"varint,3,opt,name=is_pb,json=isPb,proto3" json:"is_pb,omitempty"`
	Anything             *any.Any `protobuf:"bytes,4,opt,name=anything,proto3" json:"anything,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Any) Reset()         { *m = Any{} }
func (m *Any) String() string { return proto.CompactTextString(m) }
func (*Any) ProtoMessage()    {}
func (*Any) Descriptor() ([]byte, []int) {
	return fileDescriptor_8caaf9c5567cb817, []int{0}
}

func (m *Any) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Any.Unmarshal(m, b)
}
func (m *Any) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Any.Marshal(b, m, deterministic)
}
func (m *Any) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Any.Merge(m, src)
}
func (m *Any) XXX_Size() int {
	return xxx_messageInfo_Any.Size(m)
}
func (m *Any) XXX_DiscardUnknown() {
	xxx_messageInfo_Any.DiscardUnknown(m)
}

var xxx_messageInfo_Any proto.InternalMessageInfo

func (m *Any) GetIsPb() bool {
	if m != nil {
		return m.IsPb
	}
	return false
}

func (m *Any) GetAnything() *any.Any {
	if m != nil {
		return m.Anything
	}
	return nil
}

func init() {
	proto.RegisterType((*Any)(nil), "jimlambrt.any.v1.Any")
}

func init() { proto.RegisterFile("any.proto", fileDescriptor_8caaf9c5567cb817) }

var fileDescriptor_8caaf9c5567cb817 = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0xcc, 0xab, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0xc8, 0xca, 0xcc, 0xcd, 0x49, 0xcc, 0x4d, 0x2a, 0x2a,
	0xd1, 0x03, 0x09, 0x96, 0x19, 0x4a, 0x49, 0xa6, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea, 0x83, 0xe5,
	0x93, 0x4a, 0xd3, 0xf4, 0xe1, 0x8a, 0x95, 0x7c, 0xb8, 0x98, 0x1d, 0xf3, 0x2a, 0x85, 0x84, 0xb9,
	0x58, 0x33, 0x8b, 0xe3, 0x0b, 0x92, 0x24, 0x98, 0x15, 0x18, 0x35, 0x38, 0x82, 0x58, 0x32, 0x8b,
	0x03, 0x92, 0x84, 0x0c, 0xb8, 0x38, 0x12, 0xf3, 0x2a, 0x4b, 0x32, 0x32, 0xf3, 0xd2, 0x25, 0x58,
	0x14, 0x18, 0x35, 0xb8, 0x8d, 0x44, 0xf4, 0x20, 0x26, 0xe9, 0xc1, 0x4c, 0xd2, 0x73, 0xcc, 0xab,
	0x0c, 0x82, 0xab, 0x72, 0x92, 0x8b, 0x92, 0x49, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce,
	0xcf, 0xd5, 0x87, 0xbb, 0x03, 0x64, 0x9f, 0x75, 0x62, 0x5e, 0x65, 0x12, 0x1b, 0x58, 0x9f, 0x31,
	0x20, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x1a, 0x82, 0x35, 0xae, 0x00, 0x00, 0x00,
}
