// Code generated by protoc-gen-go. DO NOT EDIT.
// source: any.proto

package any

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Any struct {
	IsPb                 bool     `protobuf:"varint,3,opt,name=is_pb,json=isPb,proto3" json:"is_pb,omitempty"`
	Anything             *any.Any `protobuf:"bytes,4,opt,name=anything,proto3" json:"anything,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Any) Reset()         { *m = Any{} }
func (m *Any) String() string { return proto.CompactTextString(m) }
func (*Any) ProtoMessage()    {}
func (*Any) Descriptor() ([]byte, []int) {
	return fileDescriptor_8caaf9c5567cb817, []int{0}
}

func (m *Any) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Any.Unmarshal(m, b)
}
func (m *Any) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Any.Marshal(b, m, deterministic)
}
func (m *Any) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Any.Merge(m, src)
}
func (m *Any) XXX_Size() int {
	return xxx_messageInfo_Any.Size(m)
}
func (m *Any) XXX_DiscardUnknown() {
	xxx_messageInfo_Any.DiscardUnknown(m)
}

var xxx_messageInfo_Any proto.InternalMessageInfo

func (m *Any) GetIsPb() bool {
	if m != nil {
		return m.IsPb
	}
	return false
}

func (m *Any) GetAnything() *any.Any {
	if m != nil {
		return m.Anything
	}
	return nil
}

type TestUser struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestUser) Reset()         { *m = TestUser{} }
func (m *TestUser) String() string { return proto.CompactTextString(m) }
func (*TestUser) ProtoMessage()    {}
func (*TestUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_8caaf9c5567cb817, []int{1}
}

func (m *TestUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestUser.Unmarshal(m, b)
}
func (m *TestUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestUser.Marshal(b, m, deterministic)
}
func (m *TestUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestUser.Merge(m, src)
}
func (m *TestUser) XXX_Size() int {
	return xxx_messageInfo_TestUser.Size(m)
}
func (m *TestUser) XXX_DiscardUnknown() {
	xxx_messageInfo_TestUser.DiscardUnknown(m)
}

var xxx_messageInfo_TestUser proto.InternalMessageInfo

func (m *TestUser) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TestUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TestUser) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *TestUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type TestCar struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Model                string   `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Mpg                  int32    `protobuf:"varint,3,opt,name=mpg,proto3" json:"mpg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestCar) Reset()         { *m = TestCar{} }
func (m *TestCar) String() string { return proto.CompactTextString(m) }
func (*TestCar) ProtoMessage()    {}
func (*TestCar) Descriptor() ([]byte, []int) {
	return fileDescriptor_8caaf9c5567cb817, []int{2}
}

func (m *TestCar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestCar.Unmarshal(m, b)
}
func (m *TestCar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestCar.Marshal(b, m, deterministic)
}
func (m *TestCar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestCar.Merge(m, src)
}
func (m *TestCar) XXX_Size() int {
	return xxx_messageInfo_TestCar.Size(m)
}
func (m *TestCar) XXX_DiscardUnknown() {
	xxx_messageInfo_TestCar.DiscardUnknown(m)
}

var xxx_messageInfo_TestCar proto.InternalMessageInfo

func (m *TestCar) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TestCar) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *TestCar) GetMpg() int32 {
	if m != nil {
		return m.Mpg
	}
	return 0
}

type TestRental struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CarId                uint32   `protobuf:"varint,2,opt,name=car_id,json=carId,proto3" json:"car_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestRental) Reset()         { *m = TestRental{} }
func (m *TestRental) String() string { return proto.CompactTextString(m) }
func (*TestRental) ProtoMessage()    {}
func (*TestRental) Descriptor() ([]byte, []int) {
	return fileDescriptor_8caaf9c5567cb817, []int{3}
}

func (m *TestRental) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestRental.Unmarshal(m, b)
}
func (m *TestRental) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestRental.Marshal(b, m, deterministic)
}
func (m *TestRental) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestRental.Merge(m, src)
}
func (m *TestRental) XXX_Size() int {
	return xxx_messageInfo_TestRental.Size(m)
}
func (m *TestRental) XXX_DiscardUnknown() {
	xxx_messageInfo_TestRental.DiscardUnknown(m)
}

var xxx_messageInfo_TestRental proto.InternalMessageInfo

func (m *TestRental) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *TestRental) GetCarId() uint32 {
	if m != nil {
		return m.CarId
	}
	return 0
}

func init() {
	proto.RegisterType((*Any)(nil), "jimlambrt.any.v1.Any")
	proto.RegisterType((*TestUser)(nil), "jimlambrt.any.v1.TestUser")
	proto.RegisterType((*TestCar)(nil), "jimlambrt.any.v1.TestCar")
	proto.RegisterType((*TestRental)(nil), "jimlambrt.any.v1.TestRental")
}

func init() { proto.RegisterFile("any.proto", fileDescriptor_8caaf9c5567cb817) }

var fileDescriptor_8caaf9c5567cb817 = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x69, 0xb7, 0x6e, 0xeb, 0x9b, 0xca, 0x88, 0x13, 0xab, 0x88, 0xd4, 0x9e, 0x7a, 0xea,
	0xfc, 0x71, 0xd4, 0xcb, 0xf4, 0x34, 0x10, 0x91, 0xa0, 0x17, 0x2f, 0x23, 0x59, 0x63, 0x16, 0x69,
	0x92, 0x92, 0xa6, 0x42, 0xff, 0x7b, 0x49, 0xaa, 0xbd, 0x78, 0x7b, 0xef, 0x93, 0xc7, 0xf7, 0x13,
	0xbe, 0x10, 0x13, 0xd5, 0x15, 0xb5, 0xd1, 0x56, 0xa3, 0xc5, 0x97, 0x90, 0x15, 0x91, 0xd4, 0xd8,
	0xc2, 0xc1, 0xef, 0x9b, 0xf3, 0x33, 0xae, 0x35, 0xaf, 0xd8, 0xca, 0xbf, 0xd3, 0xf6, 0x73, 0x35,
	0x1c, 0x67, 0xcf, 0x30, 0x5a, 0xab, 0x0e, 0x1d, 0x43, 0x24, 0x9a, 0x6d, 0x4d, 0x93, 0x51, 0x1a,
	0xe4, 0x33, 0x3c, 0x16, 0xcd, 0x2b, 0x45, 0xd7, 0x30, 0x23, 0xaa, 0xb3, 0x7b, 0xa1, 0x78, 0x32,
	0x4e, 0x83, 0x7c, 0x7e, 0xbb, 0x2c, 0xfa, 0xa4, 0xe2, 0x2f, 0xa9, 0x58, 0xab, 0x0e, 0x0f, 0x57,
	0x19, 0x87, 0xd9, 0x1b, 0x6b, 0xec, 0x7b, 0xc3, 0x0c, 0x3a, 0x82, 0x50, 0x94, 0x49, 0x90, 0x06,
	0xf9, 0x21, 0x0e, 0x45, 0x89, 0x10, 0x8c, 0x15, 0x91, 0x2c, 0x09, 0xd3, 0x20, 0x8f, 0xb1, 0x9f,
	0xd1, 0x15, 0x1c, 0xd4, 0x7b, 0xad, 0xd8, 0x56, 0xb5, 0x92, 0x32, 0xe3, 0xed, 0x31, 0x9e, 0x7b,
	0xf6, 0xe2, 0x11, 0x5a, 0x42, 0xc4, 0x24, 0x11, 0x95, 0xff, 0x41, 0x8c, 0xfb, 0x25, 0x5b, 0xc3,
	0xd4, 0x89, 0x9e, 0xc8, 0x7f, 0xcf, 0x12, 0x22, 0xa9, 0x4b, 0x56, 0xfd, 0x8a, 0xfa, 0x05, 0x2d,
	0x60, 0x24, 0x6b, 0xee, 0x05, 0x11, 0x76, 0x63, 0xf6, 0x00, 0xe0, 0x22, 0x30, 0x53, 0x96, 0x54,
	0xe8, 0x14, 0xa6, 0x6d, 0xc3, 0xcc, 0x76, 0x88, 0x9a, 0xb8, 0x75, 0x53, 0xa2, 0x13, 0x98, 0xec,
	0x88, 0xe7, 0xa1, 0xe7, 0xd1, 0x8e, 0x98, 0x4d, 0xf9, 0x78, 0xf9, 0x71, 0xc1, 0x85, 0xdd, 0xb7,
	0xb4, 0xd8, 0x69, 0xb9, 0x1a, 0x1a, 0x77, 0xcd, 0xde, 0x13, 0xd5, 0xd1, 0x89, 0x6f, 0xe8, 0xee,
	0x27, 0x00, 0x00, 0xff, 0xff, 0x67, 0x60, 0x04, 0xeb, 0x98, 0x01, 0x00, 0x00,
}
