// Code generated by protoc-gen-go. DO NOT EDIT.
// source: any_test/any_test.proto

package any_test

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TestUser struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestUser) Reset()         { *m = TestUser{} }
func (m *TestUser) String() string { return proto.CompactTextString(m) }
func (*TestUser) ProtoMessage()    {}
func (*TestUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_749389603a6d535e, []int{0}
}

func (m *TestUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestUser.Unmarshal(m, b)
}
func (m *TestUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestUser.Marshal(b, m, deterministic)
}
func (m *TestUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestUser.Merge(m, src)
}
func (m *TestUser) XXX_Size() int {
	return xxx_messageInfo_TestUser.Size(m)
}
func (m *TestUser) XXX_DiscardUnknown() {
	xxx_messageInfo_TestUser.DiscardUnknown(m)
}

var xxx_messageInfo_TestUser proto.InternalMessageInfo

func (m *TestUser) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TestUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TestUser) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *TestUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type TestCar struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Model                string   `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Mpg                  int32    `protobuf:"varint,3,opt,name=mpg,proto3" json:"mpg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestCar) Reset()         { *m = TestCar{} }
func (m *TestCar) String() string { return proto.CompactTextString(m) }
func (*TestCar) ProtoMessage()    {}
func (*TestCar) Descriptor() ([]byte, []int) {
	return fileDescriptor_749389603a6d535e, []int{1}
}

func (m *TestCar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestCar.Unmarshal(m, b)
}
func (m *TestCar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestCar.Marshal(b, m, deterministic)
}
func (m *TestCar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestCar.Merge(m, src)
}
func (m *TestCar) XXX_Size() int {
	return xxx_messageInfo_TestCar.Size(m)
}
func (m *TestCar) XXX_DiscardUnknown() {
	xxx_messageInfo_TestCar.DiscardUnknown(m)
}

var xxx_messageInfo_TestCar proto.InternalMessageInfo

func (m *TestCar) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TestCar) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *TestCar) GetMpg() int32 {
	if m != nil {
		return m.Mpg
	}
	return 0
}

type TestRental struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CarId                uint32   `protobuf:"varint,2,opt,name=car_id,json=carId,proto3" json:"car_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestRental) Reset()         { *m = TestRental{} }
func (m *TestRental) String() string { return proto.CompactTextString(m) }
func (*TestRental) ProtoMessage()    {}
func (*TestRental) Descriptor() ([]byte, []int) {
	return fileDescriptor_749389603a6d535e, []int{2}
}

func (m *TestRental) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestRental.Unmarshal(m, b)
}
func (m *TestRental) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestRental.Marshal(b, m, deterministic)
}
func (m *TestRental) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestRental.Merge(m, src)
}
func (m *TestRental) XXX_Size() int {
	return xxx_messageInfo_TestRental.Size(m)
}
func (m *TestRental) XXX_DiscardUnknown() {
	xxx_messageInfo_TestRental.DiscardUnknown(m)
}

var xxx_messageInfo_TestRental proto.InternalMessageInfo

func (m *TestRental) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *TestRental) GetCarId() uint32 {
	if m != nil {
		return m.CarId
	}
	return 0
}

func init() {
	proto.RegisterType((*TestUser)(nil), "jimlambrt.any.v1.TestUser")
	proto.RegisterType((*TestCar)(nil), "jimlambrt.any.v1.TestCar")
	proto.RegisterType((*TestRental)(nil), "jimlambrt.any.v1.TestRental")
}

func init() { proto.RegisterFile("any_test/any_test.proto", fileDescriptor_749389603a6d535e) }

var fileDescriptor_749389603a6d535e = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xcf, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x49, 0xda, 0xa4, 0x3a, 0xfe, 0xa0, 0x2c, 0x95, 0xe6, 0x58, 0x73, 0x90, 0x9c, 0x52,
	0xc4, 0xa3, 0x5e, 0xd4, 0x53, 0x2f, 0x1e, 0x82, 0x5e, 0xbc, 0x84, 0x49, 0x76, 0x48, 0x57, 0xb2,
	0xbb, 0x61, 0xb3, 0x11, 0xfa, 0xdf, 0x4b, 0xa6, 0x36, 0x97, 0xde, 0xde, 0xfb, 0x06, 0xe6, 0x83,
	0x07, 0x6b, 0x34, 0x87, 0xd2, 0x53, 0xef, 0xb7, 0xa7, 0x90, 0x77, 0xce, 0x7a, 0x2b, 0x96, 0x3f,
	0x4a, 0xb7, 0xa8, 0x2b, 0xe7, 0x73, 0x34, 0x87, 0xfc, 0xf7, 0x31, 0x6d, 0xe0, 0xe2, 0x93, 0x7a,
	0xff, 0xd5, 0x93, 0x13, 0xb7, 0x10, 0x2a, 0x99, 0x04, 0x9b, 0x20, 0xbb, 0x29, 0x42, 0x25, 0x85,
	0x80, 0xb9, 0x41, 0x4d, 0x49, 0xb8, 0x09, 0xb2, 0xcb, 0x82, 0xb3, 0xb8, 0x87, 0xeb, 0x6e, 0x6f,
	0x0d, 0x95, 0x66, 0xd0, 0x15, 0xb9, 0x64, 0xc6, 0xb7, 0x2b, 0x66, 0x1f, 0x8c, 0xc4, 0x0a, 0x22,
	0xd2, 0xa8, 0xda, 0x64, 0xce, 0xb7, 0x63, 0x49, 0x5f, 0x61, 0x31, 0x8a, 0xde, 0xf1, 0xdc, 0xb3,
	0x82, 0x48, 0x5b, 0x49, 0xed, 0xbf, 0xe8, 0x58, 0xc4, 0x12, 0x66, 0xba, 0x6b, 0x58, 0x10, 0x15,
	0x63, 0x4c, 0x5f, 0x00, 0xc6, 0x17, 0x05, 0x19, 0x8f, 0xad, 0x58, 0xc3, 0x62, 0xe8, 0xc9, 0x95,
	0xd3, 0xab, 0x78, 0xac, 0x3b, 0x29, 0xee, 0x20, 0xae, 0x91, 0x79, 0xc8, 0x3c, 0xaa, 0xd1, 0xed,
	0xe4, 0x5b, 0xf6, 0xfd, 0xd0, 0x28, 0xbf, 0x1f, 0xaa, 0xbc, 0xb6, 0x7a, 0x3b, 0x0d, 0x31, 0x4d,
	0xf4, 0x7c, 0x0a, 0x55, 0xcc, 0x63, 0x3d, 0xfd, 0x05, 0x00, 0x00, 0xff, 0xff, 0x07, 0x94, 0x21,
	0xee, 0x47, 0x01, 0x00, 0x00,
}
